version: '3.9'

services:
  
  db:
    container_name: postgresql_db
    image: postgres
    restart: always
    ports:
      - 8001:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
  
  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - 8002:6379
  
  app:
    container_name: app
    env_file:
      - .env
    build: .
    command: "uvicorn app:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/code
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
    