"""add note field in watchlist

Revision ID: 3cd85fdf9d36
Revises: 758bbd8299bf
Create Date: 2022-05-29 22:52:01.785621

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3cd85fdf9d36'
down_revision = '758bbd8299bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watchlist', sa.Column('note', mysql.LONGTEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('watchlist', 'note')
    # ### end Alembic commands ###
