"""add note field in watchlist

Revision ID: 3f45059124eb
Revises: 758bbd8299bf
Create Date: 2022-05-29 22:53:40.339897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f45059124eb'
down_revision = '758bbd8299bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watchlist', sa.Column('note', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('watchlist', 'note')
    # ### end Alembic commands ###
